{% set name = "jsonsubschema" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsonsubschema-{{ version }}.tar.gz
  sha256: 852e0878842122a046fce5b3db1bfb801a26de20a2dfaebd8df20f366a762d2c

build:
  entry_points:
    - jsonsubschema=jsonsubschema.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - portion
    - greenery <=3.3.3
    - jsonschema
    - jsonref

test:
  imports:
    - jsonsubschema
  commands:
    - pip check
    - jsonsubschema --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/jsonsubschema
  summary: A tool to check whether a JSON schema is subset/subschema of another JSON schema
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - josk0
